# Generated by Django 2.0.7 on 2018-07-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField()),
                ('preço', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
